[project]
name = "flaskr"
version = "1.0.0"
description = "A very basic Flask app to control Raspberry PI connected RGB lights"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"